from datetime import date, timedelta

from django.core.management.base import BaseCommand
from django.utils import timezone

from core.models import Application, AttendanceRecord, Scholar, User


class Command(BaseCommand):
    help = 'Create demo users, scholars, attendance records, and applications.'

    def handle(self, *args, **options):
        admin, _ = User.objects.get_or_create(
            username='admin_demo',
            defaults={
                'email': 'admin.demo@example.com',
                'role': 'admin',
                'is_staff': True,
                'is_superuser': True,
            },
        )
        admin.set_password('AdminDemo123!')
        admin.role = 'admin'
        admin.is_staff = True
        admin.is_superuser = True
        admin.save()

        staff, _ = User.objects.get_or_create(
            username='staff_demo',
            defaults={'email': 'staff.demo@example.com', 'role': 'staff'},
        )
        staff.set_password('StaffDemo123!')
        staff.role = 'staff'
        staff.save()

        scholars = [
            {
                'scholar_id': 'SCH-1001',
                'first_name': 'Mika',
                'last_name': 'Dela Cruz',
                'date_of_birth': date(2004, 3, 12),
                'sex': 'female',
                'address': 'Barangay 1, Sample City',
                'email': 'mika@example.com',
                'phone': '09170001001',
                'course': 'BS Information Technology',
                'year_level': '2',
                'status': 'active',
            },
            {
                'scholar_id': 'SCH-1002',
                'first_name': 'Luis',
                'last_name': 'Reyes',
                'date_of_birth': date(2003, 8, 21),
                'sex': 'male',
                'address': 'Barangay 2, Sample City',
                'email': 'luis@example.com',
                'phone': '09170001002',
                'course': 'BS Accountancy',
                'year_level': '3',
                'status': 'probation',
            },
            {
                'scholar_id': 'SCH-1003',
                'first_name': 'Rina',
                'last_name': 'Santos',
                'date_of_birth': date(2005, 1, 9),
                'sex': 'female',
                'address': 'Barangay 3, Sample City',
                'email': 'rina@example.com',
                'phone': '09170001003',
                'course': 'BS Education',
                'year_level': '1',
                'status': 'active',
            },
        ]

        scholar_objects = []
        for data in scholars:
            scholar, _ = Scholar.objects.update_or_create(
                scholar_id=data['scholar_id'],
                defaults={**data, 'assigned_to': staff, 'date_enrolled': timezone.localdate()},
            )
            scholar_objects.append(scholar)

        today = timezone.localdate()
        for index, scholar in enumerate(scholar_objects):
            AttendanceRecord.objects.update_or_create(
                scholar=scholar,
                attendance_date=today - timedelta(days=index),
                defaults={'status': 'present' if index != 1 else 'late', 'notes': 'Demo attendance record'},
            )

        statuses = ['approved', 'under_review', 'pending']
        for index, scholar in enumerate(scholar_objects, start=1):
            status = statuses[index - 1]
            Application.objects.update_or_create(
                application_id=f'APP-2026-{index:03d}',
                defaults={
                    'scholar': scholar,
                    'submitted_by': staff,
                    'reviewed_by': admin if status == 'approved' else None,
                    'student_notes': 'Demo application entry.',
                    'parent_name': f'Parent {scholar.last_name}',
                    'parent_relation': 'Parent',
                    'parent_phone': f'09179990{index:03d}',
                    'parent_email': f'parent{index}@example.com',
                    'commitment_amount': 1500 * index,
                    'status': status,
                    'reviewed_at': timezone.now() if status == 'approved' else None,
                    'remarks': 'Generated by seed_demo command.',
                },
            )

        self.stdout.write(self.style.SUCCESS('Demo data created.'))
        self.stdout.write('Admin login: admin_demo / AdminDemo123!')
        self.stdout.write('Staff login: staff_demo / StaffDemo123!')
