databases:
  - name: scholarship-management-db
    plan: free

services:
  - type: web
    name: scholarship-management
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py ensure_accounts
    startCommand: gunicorn scholarship_management.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: myproject-jc1o.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://myproject-jc1o.onrender.com
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: aldrin.duco2526@gmail.com
      - key: STAFF_USERNAME
        value: staff
      - key: STAFF_PASSWORD
        sync: false
      - key: STAFF_EMAIL
        value: aldrin.duco2526@gmail.com
      - key: DATABASE_URL
        fromDatabase:
          name: scholarship-management-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECURE_SSL_REDIRECT
        value: True
      - key: SECURE_HSTS_SECONDS
        value: 31536000
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: True
      - key: SECURE_HSTS_PRELOAD
        value: True
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_USE_SSL
        value: False
      - key: EMAIL_HOST_USER
        value: aldrin.duco2526@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: aldrin.duco2526@gmail.com
      - key: EMAIL_TIMEOUT
        value: 8
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
