# Generated by Django 5.2.16 on 2026-07-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_application_commitment_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scholar',
            name='sex',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=20),
        ),
    ]
