# Generated by Django 5.2.16 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scholar_address_scholar_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='year_level',
            field=models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4')], max_length=4),
        ),
    ]
